services:
  webmin_bind:
    container_name: webmin_bind
    hostname: bind
    network_mode: bridge
    image: rickyelopez/webmin-bind
    build: .
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - 10000:10000/tcp
    volumes:
      - ./data:/data
    environment:
      - WEBMIN_ENABLED=true
      - WEBMIN_INIT_SSL_ENABLED=false
      - WEBMIN_INIT_REFERERS=dns.domain.com
      - WEBMIN_INIT_REDIRECT_PORT=10000
      - ROOT_PASSWORD=password
      - TZ=America/Los_Angeles
