name: Docker Build Main
on:
  push:
    paths:
      - '.github/workflows/*'
      - 'Dockerfile'
      - 'entrypoint.sh'
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  buildx:
    name: Buildx Multiarch Job
    runs-on: ubuntu-latest
    environment: env
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.branch }}
      - name: Dockerhub login
        run: echo "${{ secrets.DOCKER_PWD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
      - uses: rlespinasse/github-slug-action@v3.x
      - name: Print slug variables
        run: |
          echo ${{ env.GITHUB_REF_SLUG }}
          echo ${{ env.GITHUB_SHA_SHORT }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Build-Push Image
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64,linux/arm/v7 \
          --tag ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:latest \
          --tag ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_REPO }}:${{ env.GITHUB_SHA_SHORT }} \
          --push . \
          --file ./Dockerfile
      - name: Update Dockerhub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PWD }}
          repository: rickyelopez/docker-webmin-bind
