name: Docker Build Main
on:
  push:
    paths:
      - '.github/workflows/*'
      - 'Dockerfile'
      - 'entrypoint.sh'
    branches:
      - 'main'
    tags:
      - v*.*.*
  workflow_dispatch:
jobs:
  build:
    name: Build Multiarch Images
    runs-on: ubuntu-latest
    environment: env
    steps:
      - name: Dockerhub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Setup image tags
        id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: rickyelopez/webmin-bind
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
          cache-from: type=registry,ref=rickyelopez/webmin-bind:latest-buildcache
          cache-to: type=registry,ref=rickyelopez/webmin-bind:latest-buildcache,mode=max
